spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:mysql://${MYSQL_SQL_HOST}:${MYSQL_SQL_PORT}/${MYSQL_SQL_DB}
    username: ${MYSQL_SQL_USERNAME}
    password: ${MYSQL_SQL_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_TOKEN_SECRET}
  access:
    duration:
      minute: ${JWT_ACCESS_TOKEN_DURATION_MINUTE}
      second: ${JWT_ACCESS_TOKEN_DURATION_SECOND}
    cookie-name: ${JWT_ACCESS_COOKIE_NAME}
  refresh:
    duration:
      day: ${JWT_REFRESH_TOKEN_DURATION_DAY}
      second: ${JWT_REFRESH_TOKEN_DURATION_SECOND}
    cookie-name: ${JWT_REFRESH_COOKIE_NAME}