#Database
MYSQL_SQL_USERNAME: root
MYSQL_SQL_PASSWORD: toor
MYSQL_SQL_HOST: localhost
MYSQL_SQL_PORT: 3306
MYSQL_SQL_DB: jwt_cookie

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#JWT TOKEN
JWT_TOKEN_SECRET: 66546A576E5A7234753778214125442A472D4B614E645267556B587032733576

JWT_ACCESS_TOKEN_DURATION_MINUTE: 5 # 5 min
JWT_ACCESS_TOKEN_DURATION_SECOND: 300 # 5 min = 300 second
JWT_REFRESH_TOKEN_DURATION_DAY: 7 # 7 day
JWT_REFRESH_TOKEN_DURATION_SECOND: 604800  # 7 day = 604800 second

JWT_ACCESS_COOKIE_NAME: access_token
JWT_REFRESH_COOKIE_NAME: refresh_token